os:
 - osx
 
 compiler:
  - gcc
  - clang
  
  before_install:
      - wget https://nginx.org/download/nginx-1.17.1.tar.gz && tar zxvf nginx-1.17.1.tar.gz
      - wget https://ftp.pcre.org/pub/pcre/pcre-8.42.tar.gz && tar xzvf pcre-8.42.tar.gz
      - wget https://www.zlib.net/zlib-1.2.11.tar.gz && tar xzvf zlib-1.2.11.tar.gz
      - wget https://www.openssl.org/source/openssl-1.1.1a.tar.gz && tar xzvf openssl-1.1.1a.tar.gz

